# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Checking Pull Request

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install pdm
      run: |
        curl -sSLO https://pdm-project.org/install-pdm.py
        curl -sSL https://pdm-project.org/install-pdm.py.sha256 | shasum -a 256 -c -
        python3 install-pdm.py
        export PATH=$HOME/.local/bin:$PATH
    - name: Install dependencies
      run: |
        pdm sync
    - name: Lint with Ruff
      run: |
        pdm run ruff check
    - name: Type check with Mypy
      run: |
        pdm run mypy src/
    - name: Test with pytest
      run: |
        pdm run pytest test/pytest
